#!/usr/bin/env php
<?php
/**
 * 易优CMS
 * ============================================================================
 * 版权所有 2016-2028 海南赞赞网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.eyoucms.com
 * ----------------------------------------------------------------------------
 * 如果商业用途务必到官方购买正版授权, 以免引起不必要的法律纠纷.
 * ============================================================================
 * Author: 小虎哥 <1105415366@qq.com>
 * Date: 2018-4-3
 */

// 站点根目录
define('ROOT_PATH', __DIR__ . '/../');
// 定义项目路径
define('APP_PATH', ROOT_PATH . 'application/');
// 数据绝对路径
define('DATA_PATH', ROOT_PATH . 'data/');
// 缓存时间
define('EYOUCMS_CACHE_TIME', 86400);
// 运行缓存
define('RUNTIME_PATH', DATA_PATH . 'runtime/');
// 序列号
define('DEFAULT_SERIALNUMBER','20180508131400oCWIoa');
// 加载框架引导文件
require __DIR__.'/../core/console.php';
